In [14]:
import pandas as pd
import numpy as np
import Recommenders as Recommender

In [23]:
df_1 = pd.read_csv('triplets_file.csv')
df_1.head(10)

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1
5  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODDNQT12A6D4F5F7E             5
6  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODXRTY12AB0180F3B             1
7  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFGUAY12AB017B0A8             1
8  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFRQTD12A81C233C0             1
9  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOHQWYZ12A6D4FA701             1

In [25]:
df_2 = pd.read_csv('song_data.csv')
df_2.head(10)

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0
5,SOZVAPQ12A8C13B63C,"Symphony No. 1 G minor ""Sinfonie Serieuse""/All...",Berwald: Symphonies Nos. 1/2/3/4,David Montgomery,0
6,SOQVRHI12A6D4FB2D7,We Have Got Love,Strictly The Best Vol. 34,Sasha / Turbulence,0
7,SOEYRFT12AB018936C,2 Da Beat Ch'yall,Da Bomb,Kris Kross,1993
8,SOPMIYT12A6D4F851E,Goodbye,Danny Boy,Joseph Locke,0
9,SOJCFMH12A8C13B0C2,Mama_ mama can't you see ?,March to cadence with the US marines,The Sun Harbor's Chorus-Documentary Recordings,0

In [17]:
final_df = df_1.merge(df_2, on = 'song_id')
final_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,7c86176941718984fed11b7c0674ff04c029b480,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
2,76235885b32c4e8c82760c340dc54f9b608d7d7e,SOAKIMP12A8C130995,3,The Cove,Thicker Than Water,Jack Johnson,0
3,250c0fa2a77bc6695046e7c47882ecd85c42d748,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
4,3f73f44560e822344b0fb7c6b463869743eb9860,SOAKIMP12A8C130995,6,The Cove,Thicker Than Water,Jack Johnson,0

In [26]:
final_df['song'] = final_df['title']+' - '+final_df['artist_name']
final_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
1,7c86176941718984fed11b7c0674ff04c029b480,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
2,76235885b32c4e8c82760c340dc54f9b608d7d7e,SOAKIMP12A8C130995,3,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
3,250c0fa2a77bc6695046e7c47882ecd85c42d748,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
4,3f73f44560e822344b0fb7c6b463869743eb9860,SOAKIMP12A8C130995,6,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson

In [27]:
# song_grouped = final_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
# song_grouped.head()

                                                song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...            78
1                           #40 - DAVE MATTHEWS BAND           338
2                                & Down - Boys Noize           373
3                          ' Cello Song - Nick Drake           103
4                        '97 Bonnie & Clyde - Eminem            93

In [28]:
# grouped_sum = song_grouped['listen_count'].sum()
# song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
# song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

,song,listen_count,percentage
7150,Sehr kosmisch - Harmonia,8277,0.396608
9168,Use Somebody - Kings Of Leon,7952,0.381035
9112,Undo - Björk,7032,0.336952
2075,Dog Days Are Over (Radio Edit) - Florence + Th...,6949,0.332975
9909,You're The One - Dwight Yoakam,6412,0.307243
...,...,...,...
3536,Historia Del Portero - Ricardo Arjona,51,0.002444
7093,Scared - Three Days Grace,51,0.002444
2154,Don´t Leave Me Now - Amparanoia,50,0.002396
3000,Ghosts (Toxic Avenger Mix) - Ladytron,48,0.002300
5830,No Creo En El Jamas - Juanes,48,0.002300

In [29]:
pr = Recommender.pop_recommend()
pr.create(final_df, 'user_id', 'song')

pr.recommend(final_df['user_id'][3])

,user_id,song,score,Rank
7150,250c0fa2a77bc6695046e7c47882ecd85c42d748,Sehr kosmisch - Harmonia,8277,1.0
9168,250c0fa2a77bc6695046e7c47882ecd85c42d748,Use Somebody - Kings Of Leon,7952,2.0
9112,250c0fa2a77bc6695046e7c47882ecd85c42d748,Undo - Björk,7032,3.0
2075,250c0fa2a77bc6695046e7c47882ecd85c42d748,Dog Days Are Over (Radio Edit) - Florence + Th...,6949,4.0
9909,250c0fa2a77bc6695046e7c47882ecd85c42d748,You're The One - Dwight Yoakam,6412,5.0
6795,250c0fa2a77bc6695046e7c47882ecd85c42d748,Revelry - Kings Of Leon,6145,6.0
7138,250c0fa2a77bc6695046e7c47882ecd85c42d748,Secrets - OneRepublic,5841,7.0
9782,250c0fa2a77bc6695046e7c47882ecd85c42d748,Yellow - Coldplay,5658,8.0
7564,250c0fa2a77bc6695046e7c47882ecd85c42d748,Somebody To Love - Justin Bieber,5546,9.0
3623,250c0fa2a77bc6695046e7c47882ecd85c42d748,Horn Concerto No. 4 in E flat K495: II. Romanc...,5385,10.0